In [8]:
# Testing L2 distance between points in training set and testing set
# Initialization 
import numpy as np
import random
num_train = 10
num_test = 3
num_dim = 3
num_type = 5
# np.random.seed(1234) # use pseudo random with a fixed seed
X_train = np.random.uniform(low=0, high=5, size=(num_train, num_dim)) # each row is one point in training set
Y_train = np.random.randint(num_type, size=(num_train,))
X_test = np.random.uniform(low=0, high=5, size=(num_test,num_dim)) # each row is one point in testing set
Y_test = np.random.randint(num_type, size=(num_test,))

# for testing
print("X_train = \n", X_train)
print("Y_train = \n", Y_train)
print("X_test = \n", X_test)
print("Y_test = \n", Y_test)
# print(X_train.shape[0])
# print(X_test.shape[0])
# print(np.sum(np.square(X_train[0,:] - X_test[0,:])))
# print(np.sum(np.square(X_train[1,:] - X_test[1,:])))



X_train = 
 [[4.21502382 0.51808873 3.87468496]
 [4.42983013 1.40516122 2.89885673]
 [0.43709389 2.93394241 4.02250336]
 [1.88628857 2.12545072 0.88299007]
 [0.91079064 0.25342262 3.56424074]
 [4.10188407 3.05313869 2.52729993]
 [4.88528487 4.32431165 3.44769623]
 [0.43573098 0.702361   4.50274617]
 [4.56830674 3.25390586 2.42262195]
 [0.90710628 2.34501333 0.48898864]]
Y_train = 
 [3 2 2 4 2 1 0 3 3 1]
X_test = 
 [[4.09568589 1.75557567 4.14282303]
 [4.52893816 3.14128056 0.74958439]
 [3.31701966 1.70990567 4.89409424]]
Y_test = 
 [4 4 2]


In [9]:
## Test fundamental matrix operations
print(X_train * X_train) # matrix multiplied by itself is actually the square of each value 
# X_train[0,:] += X_train[1,:] # add a row by some other row

X_train[1,:] += X_test[:,0] * 3
print(X_train)


[[17.76642578  0.26841593 15.01318358]
 [19.62339497  1.97447807  8.40337034]
 [ 0.19105107  8.60801806 16.18053327]
 [ 3.55808459  4.51754076  0.77967146]
 [ 0.8295396   0.06422302 12.70381207]
 [16.82545296  9.32165584  6.38724493]
 [23.86600825 18.69967128 11.88660929]
 [ 0.18986148  0.49331098 20.27472307]
 [20.86942647 10.58790334  5.8690971 ]
 [ 0.8228418   5.4990875   0.23910989]]
[[ 4.21502382  0.51808873  3.87468496]
 [16.71688779 14.9919757  12.8499157 ]
 [ 0.43709389  2.93394241  4.02250336]
 [ 1.88628857  2.12545072  0.88299007]
 [ 0.91079064  0.25342262  3.56424074]
 [ 4.10188407  3.05313869  2.52729993]
 [ 4.88528487  4.32431165  3.44769623]
 [ 0.43573098  0.702361    4.50274617]
 [ 4.56830674  3.25390586  2.42262195]
 [ 0.90710628  2.34501333  0.48898864]]


In [ ]:
## Testing two-loop L2 distance
dist = np.zeros((num_test, num_train))
for i in range(num_test):
    for j in range(num_train):
        dist[i,j] = np.sqrt(np.sum(np.square(X_test[i,:] - X_train[j,:])))
print(dist)

In [ ]:
## Testing one-loop L2 distance
for i in range(num_test):
    dist[i,:] = np.sqrt(np.sum(np.square(X_train - X_test[i,:]), axis=1))
print(dist)

In [ ]:
## Testing no-loop L2 distance: using equation (a-b)^2 = a^2 + b^2 - 2ab
test_sum = np.sum(np.square(X_test), axis=1) # sum of squares
test_sum = np.reshape(test_sum, (num_test, 1)) # reshape the row vector as a one-column matrix
test_sqmat = np.tile(test_sum, (1, num_train)) # repeat column for `num_train` times to create matrix [a^2]

train_sum = np.sum(np.square(X_train), axis=1) # similar for training set
train_sum = np.reshape(train_sum, (1, num_train))
train_sqmat = np.tile(train_sum, (num_test, 1)) # create matrix [b^2]

dist = np.sqrt(test_sqmat + train_sqmat - 2 * X_test.dot(X_train.transpose()))

print(dist)

# print( - 2 * X_test * X_train.transpose())

# print(stest)
# stest = np.repeat(stest, 2)

# print(stest)
# print(stest.transpose())


In [ ]:
# convert a range() to a vector
print(list(range(num_train)))

In [ ]:
## Count occurance number of each value in a list/array.
a = np.array([1,2,3,2,10])

# Method 1: count occurances directly.
# unique are values, counts are occurances/frequences
(unique,counts) = np.unique(a, return_counts=True)
print(unique)
print(counts)

# Method 2: count number of values in each bin with size 1.
# Bins start from 0 and ends in maximum value + 1.
# For instance, all 3s are in the 3th bin.
# Cleary, np.bincount can only be used to count occurances of POSITIVE values.
counts = np.bincount(a)
print(counts)
most_frequent = np.argmax(counts) # index of most frequent value is also the value itself 
print(most_frequent)

# Test in kNN
k = 4
for i in range(num_test):
    closest_y = Y_train[np.argsort(dist[i,:])[0:k]] # labels of the closest k neighbors
    print(closest_y)
    counts = np.bincount(closest_y) # count number of occurance in bins (smallest to largest), each with size 1
    print(np.argmax(counts)) # return max occurance (if multiple max, then return the first one)
    

In [ ]:
## Array split
num_folds = 5
X_train_folds = np.array_split(X_train, num_folds) # split array by rows
Y_train_folds = np.array_split(Y_train, num_folds) 

print(X_train_folds)
print(Y_train_folds)
    

In [ ]:
## Delete some rows/columns in an array
num_folds = 5
fold_len = int(X_train.shape[0] / num_folds) # convert to int
for i in range(num_folds):
    # `np.s_[a:b]` sets indices from a to b in `np.delete()`. It equals to `slice(a, b)`
    # Note that a simple `[a:b]` doesn't work here.
    X_train_new = np.delete(X_train, np.s_[(i*fold_len):((i+1)*fold_len)], axis=0)
    Y_train_new = np.delete(Y_train, np.s_[(i*fold_len):((i+1)*fold_len)], axis=0)
#     print(X_train_new)
#     print(X_train_folds[i])
#     print(Y_train_new)
#     print(Y_train_folds[i])
#     print("-----------")


In [ ]:
## Test dictionary
k_choices = [1, 3, 5, 8, 10, 12, 15, 20, 50, 100]
k_to_accuracies = {}
for k in k_choices:
    accuracy = []
    for i in range(num_folds):
        accuracy.append(i) # add integer into a list
    k_to_accuracies[k] = accuracy # mapping int to a list
    print(k_to_accuracies[k])
    
